POST http://localhost:3000/login/ 
Content-Type:application/json 

{
    "username":"christopher_phillips",
    "password":"christy@123"
}

###
GET http://localhost:3000/states/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgzNzA4ODMwfQ.VT8wiFa5nYhXr79ROZGAiA660Ou0I0jY3Couoh9YpZo

###
GET http://localhost:3000/states/8 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgzNzA4ODMwfQ.VT8wiFa5nYhXr79ROZGAiA660Ou0I0jY3Couoh9YpZo


###
post http://localhost:3000/districts/
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgzNzA4ODMwfQ.VT8wiFa5nYhXr79ROZGAiA660Ou0I0jY3Couoh9YpZo

{
    "districtName":"Bagalkot",
    "stateId":3,
    "cases":2323,
    "cured":2000,
    "active":315,
    "deaths":8
}

###
GET http://localhost:3000/districts/767
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgzNzA4ODMwfQ.VT8wiFa5nYhXr79ROZGAiA660Ou0I0jY3Couoh9YpZo

###
DELETE http://localhost:3000/districts/765
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgzNzA4ODMwfQ.VT8wiFa5nYhXr79ROZGAiA660Ou0I0jY3Couoh9YpZo

###
put http://localhost:3000/districts/767/
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgzNzA4ODMwfQ.VT8wiFa5nYhXr79ROZGAiA660Ou0I0jY3Couoh9YpZo

{
    "districtName":"Nadia",
    "stateId":3,
    "cases":9628,
    "cured":6524,
    "active":3000,
    "deaths":104
}

###
GET http://localhost:3000/states/8/stats/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgzNzA4ODMwfQ.VT8wiFa5nYhXr79ROZGAiA660Ou0I0jY3Couoh9YpZo
